version: '3.3'
services:

  function-example:
    image: romualdrousseau/function-example
    environment:
      MQTT_HOST: mosquitto
      MQTT_PASSWORD: changeit
      MQTT_USERNAME: publisher
      PYTHONUNBUFFERED: '1'
      REDIS_HOST: redis
      REDIS_PASSWORD: changeit
    networks:
     - node-red_default
    logging:
      driver: json-file
    volumes:
     - /mnt/media/blob-data:/var/blob/data

networks:
  node-red_default:
    external: true
