
run: clean import
    poetry run python src/cleantaiwan

clean:
    rm -rf data/*

import:
    cp -R data.orig/* data/

export:
    gsutil -m cp -r data/* "gs://em52-bk-dataloader-rawdata-uat-6wsa/tw1/5c6534a824aa9a0001dd853a/"

